modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_title}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.endlessmusic]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endlessmusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.endlessmusic]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.endlessmusic]]
modId = "cloth_config"
mandatory = false
versionRange = "[11.1.106,)"
ordering = "AFTER"
side = "BOTH"