plugins {
	id("mod-platform")
	id("net.minecraftforge.gradle")
	id("net.minecraftforge.renamer")
	id("net.minecraftforge.jarjar")
}

stonecutter {
	val (version, loader) = current.project.split('-', limit = 2)
	properties.tags(version, loader)

	replacements.string(current.parsed >= "1.21.11") {
		replace("ResourceLocation", "Identifier")
		replace("location()", "identifier()")
	}
}

platform {
	loader = "forge"
	dependencies {
		required("minecraft") {
			forgeLikeVersionRange = prop("deps.minecraft")
		}
		required("forge") {
			forgeLikeVersionRange.set("[1,)")
		}
	}
}

//version = "${prop("deps.minecraft")}-${prop("deps.forge")}"
//group = prop("mod.group")
//base.archivesName = prop("mod.id")

if (stonecutter.eval(stonecutter.current.version, "<1.20.5")) {

	renamer.enableMixinRefmaps {
		// Test source set SHOULDN'T be used for the refmaps (circular dependencies with kotlin for some reason)
		config("${prop("mod.id")}.mixins.json")
		source(sourceSets.main.get(), prop("mod.id"))
		jar(project.tasks.named(JavaPlugin.JAR_TASK_NAME, Jar::class.java))
	}

	afterEvaluate {
		minecraft.runs.forEach { r ->
			renamer.mixin.run(r)
		}
	}

	renamer.classes(tasks.named<Jar>("jar")) {
		output.set(tasks.named<Jar>("jar").get().archiveFile)
		dependsOn("jarJar")
		// We need to use the generated mappings, which includes things generated by the annotation processor
		mappings(renamer.mixin.generatedMappings)
	}

	// Fixes the maven publishing using a broken jar
//	tasks.named<Jar>("sourcesJar") {
//		dependsOn("renameJar")
//	}
} else {
	// `mod-platform` applies Java and creates this task during its deferred
	// configuration. Configure it when it exists instead of looking it up
	// immediately while this build script is being evaluated.
	tasks.withType<Jar>().configureEach {
		if (name == "sourcesJar") dependsOn("jarJar")
	}
}

jarJar.register() {
	archiveClassifier = null
}

minecraft {
	mappings("official", prop("deps.minecraft"))
	version = "${stonecutter.current.version}-${prop("deps.forge")}"

	accessTransformers = files(getAccessFile(AccessType.TRANSFORMER))
	runs {
		configureEach {
			workingDir.convention(layout.projectDirectory.dir("run"))
		}
		register("client") {
			systemProperty("forge.enabledGameTestNamespaces", prop("mod.id"))
			args("--mixin.config", "${prop("mod.id")}.mixins.json")
		}
	}
}

repositories {
	minecraft.mavenizer(this)
	maven(fg.forgeMaven)
	maven(fg.minecraftLibsMaven)
	mavenCentral()
}

dependencies {
	implementation(minecraft.dependency("net.minecraftforge:forge:${prop("deps.minecraft")}-${prop("deps.forge")}"))
	annotationProcessor("org.spongepowered:mixin:${libs.versions.mixin.get()}:processor")
	compileOnly(libs.mixinextras.common)
	annotationProcessor(libs.mixinextras.common)
	implementation(libs.mixinextras.forge)
	"jarJar"(libs.mixinextras.forge)
}

if (stonecutter.eval(stonecutter.current.version, "<1.20.5")) {
	renamer.mappings(minecraft.dependency.toSrg.get())
}
// ForgeGradle 7.0.35 derives this task output from its own outputDirectory.
// Gradle 9 rejects that self-referential mapped provider while calculating task
// properties, so provide runsJson explicitly.
tasks.configureEach {
	if (name == "slimeLauncherMetadataForForge") {
		@Suppress("UNCHECKED_CAST")
		val outputDirectory = javaClass.methods
			.first { it.name == "getOutputDirectory" }
			.invoke(this) as DirectoryProperty
		@Suppress("UNCHECKED_CAST")
		val runsJson = javaClass.methods
			.first { it.name == "getRunsJson" }
			.invoke(this) as RegularFileProperty
		val metadataDirectory = layout.buildDirectory.dir("forgegradle/slimeLauncherMetadata")
		outputDirectory.set(metadataDirectory)
		runsJson.set(metadataDirectory.map { it.file("launcher/runs.json") })
	}
}

tasks.withType<JavaCompile>().configureEach {
	options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}
