files:
  - source: /src/main/resources/assets/constantmusic/lang/en_us.json
    translation: /src/main/resources/assets/constantmusic/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        ach: ach_ug
        aa: aa_er
        af: af_za
        ak: ak_gh
        tw: tw_tw
        sq: sq_al
        am: am_et
        ar: ar_sa
        ar-BH: ar_bh
        ar-EG: ar_eg
        ar-SA: ar_sa
        ar-YE: ar_ye
        an: an_es
        hy-AM: hy_am
        frp: frp_it
        as: as_in
        ast: ast_es
        tay: tay_tw
        av: av_da
        ae: ae_ir
        ay: ay_bo
        az: az_az
        ban: ban_id
        bal: bal_ba
        bm: bm_ml
        ba: ba_ru
        eu: eu_es
        be: be_by
        bn: bn_bd
        bn-IN: bn_in
        ber: ber_dz
        bh: bh_in
        bfo: bfo_bf
        bi: bi_vu
        bs: bs_ba
        br-FR: br_fr
        bg: bg_bg
        my: my_mm
        ca: ca_es
        ceb: ceb_ph
        ch: ch_gu
        ce: ce_ce
        chr: chr_us
        ny: ny_mw
        zh-CN: zh_cn
        zh-SG: zh_sg
        zh-TW: zh_tw
        zh-HK: zh_hk
        zh-MO: zh_mo
        cv: cv_cu
        kw: kw_gb
        co: co_fr
        cr: cr_nt
        hr: hr_hr
        cs: cs_cz
        da: da_dk
        fa-AF: fa_af
        dv: dv_mv
        nl: nl_nl
        nl-BE: nl_be
        nl-SR: nl_sr
        dz: dz_bt
        en: en_us
        en-UD: en_ud
        en-AR: en_ar
        en-AU: en_au
        en-BZ: en_bz
        en-CA: en_ca
        en-CB: en_cb
        en-CN: en_cn
        en-DK: en_dk
        en-HK: en_hk
        en-IN: en_in
        en-ID: en_id
        en-IE: en_ie
        en-JM: en_jm
        en-JA: en_ja
        en-MY: en_my
        en-NZ: en_nz
        en-NO: en_no
        en-PH: en_ph
        en-PR: en_pr
        en-SG: en_sg
        en-ZA: en_za
        en-SE: en_se
        en-GB: en_gb
        en-US: en_us
        en-ZW: en_zw
        eo: eo_uy
        et: et_ee
        ee: ee_gh
        fo: fo_fo
        fj: fj_fj
        fil: fil_ph
        fi: fi_fi
        vls-BE: vls_be
        fra-DE: fra_de
        fr: fr_fr
        fr-BE: fr_be
        fr-CA: fr_ca
        fr-LU: fr_lu
        fr-QC: fr_qc
        fr-CH: fr_ch
        fy-NL: fy_nl
        fur-IT: fur_it
        ff: ff_za
        gaa: gaa_gh
        gl: gl_es
        ka: ka_ge
        de: de_de
        de-AT: de_at
        de-BE: de_be
        de-LI: de_li
        de-LU: de_lu
        de-CH: de_ch
        got: got_de
        el: el_gr
        el-CY: el_cy
        kl: kl_gl
        gn: gn_py
        gu-IN: gu_in
        ht: ht_ht
        ha: ha_hg
        haw: haw_us
        he: he_il
        hz: hz_na
        hil: hil_ph
        hi: hi_in
        ho: ho_pg
        hmn: hmn_cn
        hu: hu_hu
        is: is_is
        ido: io_en
        ig: ig_ng
        ilo: ilo_ph
        id: id_id
        iu: iu_nu
        ga-IE: ga_ie
        it: it_it
        it-CH: it_ch
        ja: ja_jp
        jv: jv_id
        quc: quc_gt
        kab: kab_kab
        kn: kn_in
        pam: pam_ph
        ks: ks_in
        ks-PK: ks_pk
        csb: csb_pl
        kk: kk_kz
        km: km_kh
        rw: rw_rw
        tlh-AA: tlh_aa
        kv: kv_ko
        kg: kg_cg
        kok: kok_in
        ko: ko_kr
        ku: ku_tr
        kmr: kmr_tr
        kj: kj_ao
        ky: ky_kg
        lo: lo_la
        la-LA: la_la
        lv: lv_lv
        lij: lij_it
        li: li_li
        ln: ln_cd
        lt: lt_lt
        jbo: jbo_en
        lol: lol_us
        nds: nds_de
        dsb-DE: dsb_de
        lg: lg_ug
        luy: luy_ke
        lb: lb_lu
        mk: mk_mk
        mai: mai_in
        mg: mg_mg
        ms: ms_my
        ms-BN: ms_bn
        ml-IN: ml_in
        mt: mt_mt
        gv: gv_im
        mi: mi_nz
        arn: arn_cl
        mr: mr_in
        mh: mh_mh
        moh: moh_ca
        mn: mn_mn
        sr-Cyrl-ME: sr_cyrl_me
        me: me_me
        mos: mos_mos
        na: na_nr
        ng: ng_na
        ne-NP: ne_np
        ne-IN: ne_in
        pcm: pcm_ng
        se: se_no
        nso: ns_za
        no: no_no
        nb: nb_no
        nn-NO: nn_no
        oc: oc_fr
        or: or_in
        oj: oj_ca
        om: om_et
        os: os_se
        pi: pi_in
        pap: pap_pap
        ps: ps_af
        fa: fa_ir
        en-PT: en_pt
        pl: pl_pl
        pt-PT: pt_pt
        pt-BR: pt_br
        pa-IN: pa_in
        pa-PK: pa_pk
        qu: qu_pe
        qya-AA: qya_aa
        ro: ro_ro
        rm-CH: rm_ch
        rn: rn_bi
        ru: ru_ru
        ru-BY: ru_by
        ru-MD: ru_md
        ry-UA: ry_ua
        ru-UA: ru_ua
        sah: sah_sah
        sg: sg_cf
        sa: sa_in
        sat: sat_in
        sc: sc_it
        sco: sco_gb
        gd: gd_gb
        sr: sr_sp
        sr-CS: sr_cs
        sh: sh_hr
        crs: crs_sc
        sn: sn_zw
        ii: ii_cn
        sd: sd_pk
        si-LK: si_lk
        sk: sk_sk
        sl: sl_si
        so: so_so
        son: son_za
        ckb: ckb_ir
        nr: nr_za
        sma: sma_no
        st: st_za
        es-ES: es_es
        es-EM: es_em
        es-AR: es_ar
        es-BO: es_bo
        es-CL: es_cl
        es-CO: es_co
        es-CR: es_cr
        es-DO: es_do
        es-EC: es_ec
        es-SV: es_sv
        es-GT: es_gt
        es-HN: es_hn
        es-419: es_419
        es-MX: es_mx
        es-NI: es_ni
        es-PA: es_pa
        es-PY: es_py
        es-PE: es_pe
        es-PR: es_pr
        es-US: es_us
        es-UY: es_uy
        es-VE: es_ve
        su: su_id
        sw: sw_ke
        sw-KE: sw_ke
        sw-TZ: sw_tz
        ss: ss_za
        sv-SE: sv_se
        sv-FI: sv_fi
        syc: syc_sy
        tl: tl_ph
        ty: ty_pf
        tg: tg_tj
        tzl: tzl_tzl
        ta: ta_in
        tt-RU: tt_ru
        te: te_in
        kdh: kdh_kdh
        th: th_th
        bo-BT: bo_bt
        ti: ti_er
        ts: ts_za
        tn: tn_za
        tr: tr_tr
        tr-CY: tr_cy
        tk: tk_tm
        uk: uk_ua
        hsb-DE: hsb_de
        ur-IN: ur_in
        ur-PK: ur_pk
        ug: ug_cn
        uz: uz_uz
        val-ES: val_es
        ve: ve_za
        vec: vec_it
        vi: vi_vn
        wa: wa_be
        cy: cy_gb
        wo: wo_sn
        xh: xh_za
        yi: yi_de
        yo: yo_ng
        zea: zea_zea
        zu: zu_za


bundles:
  - 2
commit_message: "chore(lang): update translations for %language% [%original_file_name%] [ci skip]"
append_commit_message: false

pull_request_title: "Localization: Update Minecraft language bundles"
pull_request_description: "Automated translation sync from Crowdin.\n\nUpdated locales: %language_names%"
pull_request_labes:
  - "crowdin"
  - "l10n"
