files:
  - source: /src/main/resources/assets/constantmusic/lang/en_us.json
    translation: /src/main/resources/assets/constantmusic/lang/%locale_with_underscore%.json
bundles:
  - 2
commit_message: "chore(lang): update translations for %language% [%locale%]"
append_commit_message: false

pull_request_title: "Localization: Update Minecraft language bundles"
pull_request_description: "Automated translation sync from Crowdin.\n\nUpdated locales: %language_names%"
