files:
  - source: /src/main/resources/assets/constantmusic/lang/en_us.json
    translation: /src/main/resources/assets/constantmusic/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        aa: aa_er
        ach: ach_ug
        ae: ae_ir
        af: af_za
        ak: ak_gh
        am: am_et
        an: an_es
        ar: ar_sa
        ar-BH: ar_bh
        ar-EG: ar_eg
        ar-SA: ar_sa
        ar-YE: ar_ye
        arn: arn_cl
        as: as_in
        ast: ast_es
        av: av_da
        ay: ay_bo
        az: az_az
        ba: ba_ru
        bal: bal_ba
        ban: ban_id
        be: be_by
        ber: ber_dz
        bfo: bfo_bf
        bg: bg_bg
        bh: bh_in
        bi: bi_vu
        bm: bm_ml
        bn: bn_bd
        bn-IN: bn_in
        bo: bo_bt
        br: br_fr
        bs: bs_ba
        ca: ca_es
        ce: ce_ce
        ceb: ceb_ph
        ch: ch_gu
        chr: chr_us
        ckb: ckb_ir
        co: co_fr
        cr: cr_nt
        crs: crs_sc
        cs: cs_cz
        csb: csb_pl
        cv: cv_cu
        cy: cy_gb
        da: da_dk
        de: de_de
        de-AT: de_at
        de-BE: de_be
        de-CH: de_ch
        de-LI: de_li
        de-LU: de_lu
        dsb: dsb_de
        dv: dv_mv
        dz: dz_bt
        ee: ee_gh
        el: el_gr
        el-CY: el_cy
        en: en_us
        en-AR: en_ar
        en-AU: en_au
        en-BZ: en_bz
        en-CA: en_ca
        en-CB: en_cb
        en-CN: en_cn
        en-DK: en_dk
        en-GB: en_gb
        en-HK: en_hk
        en-ID: en_id
        en-IE: en_ie
        en-IN: en_in
        en-JA: en_ja
        en-JM: en_jm
        en-MY: en_my
        en-NO: en_no
        en-NZ: en_nz
        en-PH: en_ph
        en-PR: en_pr
        en-SE: en_se
        en-SG: en_sg
        en-US: en_us
        en-ZA: en_za
        en-ZW: en_zw
        eo: eo_uy
        es: es_es
        es-419: es_419
        es-AR: es_ar
        es-BO: es_bo
        es-CL: es_cl
        es-CO: es_co
        es-CR: es_cr
        es-DO: es_do
        es-EC: es_ec
        es-EM: es_em
        es-GT: es_gt
        es-HN: es_hn
        es-MX: es_mx
        es-NI: es_ni
        es-PA: es_pa
        es-PE: es_pe
        es-PR: es_pr
        es-PY: es_py
        es-SV: es_sv
        es-US: es_us
        es-UY: es_uy
        es-VE: es_ve
        et: et_ee
        eu: eu_es
        fa: fa_ir
        fa-AF: fa_af
        ff: ff_za
        fi: fi_fi
        fil: fil_ph
        fj: fj_fj
        fo: fo_fo
        fr: fr_fr
        fr-BE: fr_be
        fr-CA: fr_ca
        fr-CH: fr_ch
        fr-LU: fr_lu
        fr-QC: fr_qc
        fra: fra_de
        frp: frp_it
        fur: fur_it
        fy: fy_nl
        ga: ga_ie
        gaa: gaa_gh
        gd: gd_gb
        gl: gl_es
        gn: gn_py
        gu: gu_in
        ha: ha_hg
        haw: haw_us
        he: he_il
        hi: hi_in
        hil: hil_ph
        hmn: hmn_cn
        ho: ho_pg
        hr: hr_hr
        hsb: hsb_de
        ht: ht_ht
        hu: hu_hu
        hy: hy_am
        hz: hz_na
        id: id_id
        ido: io_en
        ig: ig_ng
        ii: ii_cn
        ilo: ilo_ph
        is: is_is
        it: it_it
        it-CH: it_ch
        iu: iu_nu
        ja: ja_jp
        jv: jv_id
        ka: ka_ge
        kab: kab_kab
        kdh: kdh_kdh
        kg: kg_cg
        kj: kj_ao
        kk: kk_kz
        kl: kl_gl
        km: km_kh
        kmr: kmr_tr
        kn: kn_in
        ko: ko_kr
        kok: kok_in
        ks: ks_in
        ks-PK: ks_pk
        ku: ku_tr
        kv: kv_ko
        kw: kw_gb
        ky: ky_kg
        la: la_la
        lb: lb_lu
        lg: lg_ug
        li: li_li
        lij: lij_it
        ln: ln_cd
        lo: lo_la
        lt: lt_lt
        luy: luy_ke
        lv: lv_lv
        mai: mai_in
        mg: mg_mg
        mh: mh_mh
        mi: mi_nz
        mk: mk_mk
        ml: ml_in
        mn: mn_mn
        mos: mos_mos
        mr: mr_in
        ms: ms_my
        ms-BN: ms_bn
        mt: mt_mt
        my: my_mm
        na: na_nr
        nb: nb_no
        nds: nds_de
        ne: ne_np
        ne-IN: ne_in
        ng: ng_na
        nl: nl_nl
        nl-BE: nl_be
        nl-SR: nl_sr
        nn-NO: nn_no
        no: no_no
        nr: nr_za
        nso: ns_za
        ny: ny_mw
        oc: oc_fr
        oj: oj_ca
        om: om_et
        or: or_in
        os: os_se
        pa: pa_in
        pa-PK: pa_pk
        pam: pam_ph
        pap: pap_pap
        pcm: pcm_ng
        pi: pi_in
        pl: pl_pl
        ps: ps_af
        pt: pt_pt
        pt-BR: pt_br
        qu: qu_pe
        quc: quc_gt
        rm: rm_ch
        rn: rn_bi
        ro: ro_ro
        ru: ru_ru
        ru-BY: ru_by
        ru-MD: ru_md
        rw: rw_rw
        sa: sa_in
        sah: sah_sah
        sat: sat_in
        sc: sc_it
        sco: sco_gb
        sd: sd_pk
        se: se_no
        sg: sg_cf
        sh: sh_hr
        si: si_lk
        sk: sk_sk
        sl: sl_si
        sma: sma_no
        sn: sn_zw
        so: so_so
        son: son_za
        sq: sq_al
        sr: srp
        sr-Cyrl: sr_cyrl
        sr-Latn: sr_latn
        ss: ss_za
        st: st_za
        su: su_id
        sv: sv_se
        sv-FI: sv_fi
        sw: sw_ke
        sw-KE: sw_ke
        sw-TZ: sw_tz
        syc: syc_sy
        ta: ta_in
        tay: tay_tw
        te: te_in
        tg: tg_tj
        th: th_th
        ti: ti_er
        tk: tk_tm
        tl: tl_ph
        tn: tn_za
        tr: tr_tr
        tr-CY: tr_cy
        ts: ts_za
        tt: tt_ru
        tw: tw_tw
        ty: ty_pf
        ug: ug_cn
        uk: uk_ua
        ur: ur_pk
        ur-IN: ur_in
        uz: uz_uz
        val: val_es
        ve: ve_za
        vec: vec_it
        vi: vi_vn
        vls: vls_be
        wa: wa_be
        wo: wo_sn
        xh: xh_za
        yi: yi_de
        yo: yo_ng
        zea: zea_zea
        zh-CN: zh_cn
        zh-HK: zh_hk
        zh-MO: zh_mo
        zh-SG: zh_sg
        zh-TW: zh_tw
        zu: zu_za

bundles:
  - 2
commit_message: "chore(lang): update translations for %language% [%original_file_name%] [ci skip]"
append_commit_message: false

pull_request_title: "Localization: Update Minecraft language bundles"
pull_request_description: "Automated translation sync from Crowdin.\n\nUpdated locales: %language_names%"
pull_request_labes:
  - "crowdin"
  - "l10n"
