org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.configuration-cache=false

stonecutter.version=0.10-alpha.12
loomx.version=0.4.3
foojay.version=1.0.0

loomx.loom_version=1.17-SNAPSHOT
kotlin.build.archivesTaskOutputAsFriendModule=false
net.minecraftforge.gradle.merge-source-sets=false
