[versions]
stonecutter = "0.10-alpha.7"
stonecutter-postprocess = "2.1-beta.8"
mod-publish = "2.1.1"
loomx = "0.4.2"
neoforge-moddev = "2.0.141"
foojay = "1.0.0"
devtools-ksp = "2.2.10-2.0.2"
kotlin-jvm = "2.2.10"
fletching-table = "0.1.0-alpha.22"
moulberry-mixinconstraints = "1.1.0"
vanniktech-maven-publish = "0.35.0"
mixin = "0.8.7"
serialization-json = "1.7.3"
serialization-toml = "0.6.0"
mixinextras = "0.5.4"
forgegradle = "[7.0.29,8.0)"
renamer = "1.1.2"
jarjar = "0.2.3"

[libraries]
kikugie-postprocess = { module = "dev.kikugie:postprocess", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { module = "me.modmuss50:mod-publish-plugin", version.ref = "mod-publish" }
kikugie-stonecutter = { module = "dev.kikugie:stonecutter", version.ref = "stonecutter" }
kikugie-loomx = { module = "dev.kikugie:loomx", version.ref = "loomx" }
foojay-resolver = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "foojay" }
fletching-table = { module = "dev.kikugie:fletching-table", version.ref = "fletching-table" }
moulberry-mixinconstraints = { module = "com.moulberry:mixinconstraints", version.ref = "moulberry-mixinconstraints" }
vanniktech-maven-publish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "vanniktech-maven-publish" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }
serialization-toml = { module = "dev.eav.tomlkt:tomlkt", version.ref = "serialization-toml" }
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras"}
mixinextras-fabric = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixinextras"}
mixinextras-forge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras"}
mixinextras-neoforge = { module = "io.github.llamalad7:mixinextras-neoforge", version.ref = "mixinextras"}

[plugins]
stonecutter = { id = "dev.kikugie.stonecutter", version.ref = "stonecutter" }
loom-back-compat = { id = "dev.kikugie.loom-back-compat", version.ref = "loomx" }
neoforged-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }
jsonlang-postprocess = { id = "dev.kikugie.postprocess.jsonlang", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
fletching-table = { id = "dev.kikugie.fletching-table", version.ref = "fletching-table" }
legacyforge-moddev = { id = "net.neoforged.moddev.legacyforge", version.ref = "neoforge-moddev" }
forgegradle = { id = "net.minecraftforge.gradle", version.ref = "forgegradle"}
renamer = { id = "net.minecraftforge.renamer", version.ref = "renamer"}
jarjar = { id = "net.minecraftforge.jarjar", version.ref = "jarjar"}
