name: Run all versions with Xvfb
on:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix_include: ${{ steps.set_matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Parse versions.json into matrix array
        id: set_matrix
        run: |
          filter='.versions[] | { mc: .version, modloader: .loaders[], java: .java } | . + { type: (if .modloader == "forge" then "lexforge" else .modloader end), regex: ".*\(.modloader).*" }'
          matrix_json=$(jq -c "[$filter]" ./versions.json)
          echo "matrix=$matrix_json" >> "$GITHUB_OUTPUT"
  build:
    uses: ./.github/workflows/build_reusable.yml
  run-matrix:
    runs-on: ubuntu-latest
    needs:
      - define-matrix
      - build

    strategy:
      fail-fast: true
      matrix:
        version: ${{ fromJSON(needs.define-matrix.outputs.matrix_include) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup JDK matching matrix target
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.version.java }}
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: wrapper

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifacts
          path: build/libs/

      - name: Create mods dir
        run: mkdir -p run/mods

      - name: List mod files
        run: ls build/libs

      - name: Copy mod jar
        run: find build/libs -type f -name "constantmusic-*-${{ matrix.version.modloader }}+${{ matrix.version.mc }}*.jar" -not -name "*-javadoc.jar" -not -name "*-sources.jar" -exec cp {} run/mods \;

      - name: Run the MC client
        uses: 3arthqu4ke/mc-runtime-test@4.5.1
        with:
          mc: ${{ matrix.version.mc }}
          modloader: ${{ matrix.version.modloader }}
          regex: ${{ matrix.version.regex }}
          java: ${{ matrix.version.java }}
          mc-runtime-test: ${{ matrix.version.type }}
          xvfb: true
          headlessmc-command: -lwjgl --jvm -Djava.awt.headless=true --retries 2
