name: Run all versions with Xvfb
on:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix_include: ${{ steps.set_matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Prepare matrix
        id: set_matrix
        uses: ./.github/actions/prepare-matrix
  build:
    uses: ./.github/workflows/build_reusable.yml
  run-matrix:
    runs-on: ubuntu-latest
    needs:
      - define-matrix
      - build

    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.define-matrix.outputs.matrix_include) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup JDK matching matrix target
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: wrapper

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifacts
          path: build/libs/

      - name: Create mods dir
        run: mkdir -p run/mods

      - name: List mod files
        run: ls build/libs

      - name: Copy mod jar
        run: find build/libs -type f -name "constantmusic-*-${{ matrix.modLoader }}+${{ matrix.version }}*.jar" -not -name "*-javadoc.jar" -not -name "*-sources.jar" -not -name "*-slim.jar" -exec cp {} run/mods \;

      - name: Run the MC client
        uses: 3arthqu4ke/mc-runtime-test@4.5.1
        with:
          mc: ${{ matrix.version }}
          modloader: ${{ matrix.modLoader }}
          regex: ${{ matrix.regex }}
          java: ${{ matrix.java }}
          mc-runtime-test: ${{ matrix.type }}
          fabric-api: ${{ matrix.fabricApi }}
          xvfb: true
          headlessmc-command: -lwjgl --jvm -Djava.awt.headless=true --retries 2
